services:
  - type: web
    name: finalwebproject
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: API_PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: study-planner-db
          property: connectionString
      - key: CLIENT_ORIGIN
        value: https://finalwebproject-b4va.onrender.com

databases:
  - name: study-planner-db
    plan: free
    databaseName: planner
    user: planner
