services:
  - type: web
    name: finalwebproject
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: API_PORT
        value: 4000
      - key: CLIENT_ORIGIN
        value: https://finalwebproject-b4va.onrender.com
